# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('host', models.CharField(blank=True, max_length=255, null=True)),
                ('event_description', models.TextField(blank=True, null=True)),
                ('iga_leg', models.CharField(blank=True, max_length=10, null=True)),
                ('press', models.NullBooleanField()),
                ('press_note', models.CharField(blank=True, max_length=255, null=True)),
                ('no_of_travelers', models.IntegerField(blank=True, null=True)),
                ('no_of_travelers_note', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventLocationPrincipalTravel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('agency', models.CharField(blank=True, max_length=255, null=True)),
                ('principal_poc', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=32, null=True)),
                ('format', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='eventlocationprincipaltravel',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.Location'),
        ),
        migrations.AddField(
            model_name='eventlocationprincipaltravel',
            name='principal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.Principal'),
        ),
        migrations.AddField(
            model_name='eventlocationprincipaltravel',
            name='travel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.Travel'),
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('agency_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('no_of_travelers', models.IntegerField(blank=True, null=True)),
                ('no_of_travelers_note', models.CharField(blank=True, max_length=32, null=True)),
                ('principal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Principal')),
            ],
        ),
        migrations.CreateModel(
            name='TripEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='iga_leg',
        ),
        migrations.RemoveField(
            model_name='event',
            name='no_of_travelers',
        ),
        migrations.RemoveField(
            model_name='event',
            name='no_of_travelers_note',
        ),
        migrations.AddField(
            model_name='tripevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Event'),
        ),
        migrations.AddField(
            model_name='tripevent',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Trip'),
        ),
        migrations.RemoveField(
            model_name='principal',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='principal_poc',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='name',
        ),
        migrations.AddField(
            model_name='principal',
            name='agency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='principal',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CountryRegion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('office_name', models.CharField(max_length=255, null=True)),
                ('agency_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.Agency')),
            ],
        ),
        migrations.AddField(
            model_name='region',
            name='agency_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.Agency'),
        ),
        migrations.AddField(
            model_name='countryregion',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.Region'),
        ),
        migrations.AddField(
            model_name='event',
            name='no_of_travelers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='no_of_travelers_note',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='cities_light_city_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.City'),
        ),
        migrations.AddField(
            model_name='event',
            name='cities_light_country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.Country'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.EventType'),
        ),
        migrations.AddField(
            model_name='principal',
            name='agency_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.Agency'),
        ),
        migrations.AddField(
            model_name='principal',
            name='career',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='principal',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='principal',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='principal',
            name='region_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.Region'),
        ),
    ]
