# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_squashed_0012_auto_20160307_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='cities_light_city_id',
            new_name='cities_light_city',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='cities_light_country_id',
            new_name='cities_light_country',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='agency_id',
            new_name='agency',
        ),
        migrations.RenameField(
            model_name='principal',
            old_name='region_id',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='agency_id',
            new_name='agency',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='principal_id',
            new_name='principal',
        ),
    ]
