# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('agency_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('no_of_travelers', models.IntegerField(blank=True, null=True)),
                ('no_of_travelers_note', models.CharField(blank=True, max_length=32, null=True)),
                ('principal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Principal')),
            ],
        ),
        migrations.CreateModel(
            name='TripEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='iga_leg',
        ),
        migrations.RemoveField(
            model_name='event',
            name='no_of_travelers',
        ),
        migrations.RemoveField(
            model_name='event',
            name='no_of_travelers_note',
        ),
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tripevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Event'),
        ),
        migrations.AddField(
            model_name='tripevent',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Trip'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.EventType'),
        ),
    ]
