# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20160307_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='principal',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='principal_poc',
        ),
        migrations.AddField(
            model_name='principal',
            name='agency_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.Agency'),
        ),
        migrations.AddField(
            model_name='principal',
            name='career',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='principal',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='principal',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='principal',
            name='region_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.Region'),
        ),
    ]
