# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20160308_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_type_id',
            new_name='event_type',
        ),
    ]
