# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20160308_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='principal',
            name='principal_poc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
