# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_remove_principal_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Region')),
            ],
        ),
    ]
