# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_principal_principal_poc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countryregion',
            old_name='country',
            new_name='cities_light_country',
        ),
        migrations.RemoveField(
            model_name='event',
            name='no_of_travelers',
        ),
        migrations.RemoveField(
            model_name='event',
            name='no_of_travelers_note',
        ),
        migrations.RemoveField(
            model_name='office',
            name='office_name',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='agency_id',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='name',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='principal_poc',
        ),
        migrations.AddField(
            model_name='office',
            name='office_long_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='office_short_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='principal',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.Agency'),
        ),
    ]
