# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
        ('travel', '0005_auto_20160309_1558'),
    ]

    def migrate_data(apps, schema_editor):
        CountryRegion = apps.get_model('travel', 'CountryRegion')
        for country_region in CountryRegion.objects.all():
            country_region.region.countries.add(country_region.cities_light_country)
            country_region.save()

        TripEvent = apps.get_model('travel', 'TripEvent')
        for trip_event in TripEvent.objects.all():
            trip_event.trip.events.add(trip_event.event)
            trip_event.save()

    operations = [
        migrations.AddField(
            model_name='region',
            name='countries',
            field=models.ManyToManyField(related_name='custom_region', to='cities_light.Country'),
        ),
        migrations.AddField(
            model_name='trip',
            name='events',
            field=models.ManyToManyField(to='travel.Event'),
        ),
        migrations.RunPython(migrate_data),
        migrations.DeleteModel(
            name='CountryRegion',
        ),
        migrations.DeleteModel(
            name='TripEvent',
        ),
    ]
