# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
        ('travel', '0005_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cities_light_city_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.City'),
        ),
        migrations.AddField(
            model_name='event',
            name='cities_light_country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.Country'),
        ),
    ]
