# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_auto_20160307_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='region_id',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
