# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_auto_20160309_1856'),
    ]

    def migrate_data(apps, schema_editor):
        Principal = apps.get_model('travel', 'Principal')
        for principal in Principal.objects.all():
            # setting these all to a default office. can tweak manually later.
            principal.office_id = 1
            principal.save()

    operations = [
        migrations.AddField(
            model_name='principal',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.Office'),
        ),
        migrations.RunPython(migrate_data),
        migrations.RemoveField(
            model_name='principal',
            name='agency',
        ),
    ]
