# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_auto_20160309_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlocationprincipaltravel',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventlocationprincipaltravel',
            name='location',
        ),
        migrations.RemoveField(
            model_name='eventlocationprincipaltravel',
            name='principal',
        ),
        migrations.RemoveField(
            model_name='eventlocationprincipaltravel',
            name='travel',
        ),
        migrations.RenameField(
            model_name='agency',
            old_name='agency_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='eventtype',
            old_name='event_type_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='office_long_name',
            new_name='long_name',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='office_short_name',
            new_name='short_name',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='region_name',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='EventLocationPrincipalTravel',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Travel',
        ),
    ]
