# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_auto_20160310_1914'),
        ('travel', '0007_auto_20160310_1634'),
    ]

    operations = [
    ]
