# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_auto_20160307_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='principal',
            name='agency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='principal',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='principal',
            name='principal_poc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
