# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_auto_20160307_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='cities_light_city_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='cities_light_country_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_type_id',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='agency_id',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='career',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='region_id',
        ),
        migrations.AddField(
            model_name='event',
            name='iga_leg',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='no_of_travelers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='no_of_travelers_note',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
