# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 22:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel', '0010_auto_20160323_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='principal',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='principal_create', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='principal',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='principal_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
    ]
