# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
        ('travel', '0011_auto_20160307_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='iga_leg',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='principal_poc',
        ),
        migrations.AddField(
            model_name='event',
            name='cities_light_city_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.City'),
        ),
        migrations.AddField(
            model_name='event',
            name='cities_light_country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.Country'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.EventType'),
        ),
        migrations.AddField(
            model_name='principal',
            name='agency_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.Agency'),
        ),
        migrations.AddField(
            model_name='principal',
            name='career',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='principal',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='principal',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='principal',
            name='region_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.Region'),
        ),
    ]
