# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def forwards(apps, schema_editor):
    Region = apps.get_model('travel', 'Region')
    db_alias = schema_editor.connection.alias
    for region in Region.objects.using(db_alias).all():
        if region.countries.count() > 0:
            region.country = list(region.countries.all())[0]
            region.save()

def backwards(apps, schema_editor):
    Region = apps.get_model('travel', 'Region')
    db_alias = schema_editor.connection.alias
    for region in Region.objects.using(db_alias).all():
        region.country_set.add(region.country)
        region.save_m2m()

class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
        ('travel', '0013_auto_20160401_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='country',
            field=models.ForeignKey(null=True, related_name='agency_region', to='cities_light.Country'),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.RemoveField(
            model_name='region',
            name='countries'
        ),
    ]
